name: Analysis
on:
  pull_request:
jobs:
  check:
    name: pre-merge-checks
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Setup Haskell
        id: setup-haskell-cabal
        uses: actions/setup-haskell@v1.1.3
        with:
          ghc-version: 8.8

      - name: Install Necessary Tools
        run: sudo apt-get install hlint

      - name: Cabal Check
        run: cabal check

      - name: Lint
        run: hlint .
